trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    az webapp up --name <Your-App-Service-Name> --resource-group <Your-Resource-Group> --runtime "PYTHON|3.10"
  displayName: 'Deploy to Azure App Service'
